export interface Startup {
    id?: number,
    nome: string,   
    descricao: string,
    metas: string,
    CNPJ?: string,
    cep: string,
    logradouro: string,
    numero: string,
    bairro: string,
    municipio: string,
    UF: string,
    siteStartup?: string,
    quantidadeFuncionario: number,
    tipoAtendimento: string,
    ticket: string,
    responsavelCadastro: string,
    Login: string,
    senha: string,
    atuacoes: string,
    Imagens : string,
    videos: string,
    Contatos: string,
}